version: "3"
services:
  jenkins:
    image: marceloweb/jenkins-docker
    privileged: true
    restart: always
    ports:
      - "8081:8080"
    environment:
      DB_HOST: db
      DB_NAME: example
      DB_USER: root
      DB_PASSWD: root
    volumes:
      - jenkins-data:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/var/jenkins_home/spring-boot-example-0.0.1-SNAPSHOT.jar"]
    links:
      - db
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
  db:
      image: mariadb
      privileged: true
      restart: always
      ports:
         - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: root
volumes:
  jenkins-data:
    driver: local
