version: "3"
services:
  jenkins:
    image: jeffersonsouza/jenkins:alpine
    privileged: true
    restart: always
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
volumes:
  jenkins-data:
    driver: local
